<script ✂prettier:content✂="CiAgICBpbXBvcnQge2ZseX0gZnJvbSAic3ZlbHRlL3RyYW5zaXRpb24iOwogICAgaW1wb3J0IHtzaG93UmVnaXN0cmF0aW9ufSBmcm9tICIkbGliL3N0YXRlcy5zdmVsdGUiOwogICAgaW1wb3J0IFJlZ2lzdHJhdGlvbiBmcm9tICIkbGliL2NvbXBvbmVudHMvUmVnaXN0cmF0aW9uLnN2ZWx0ZSI7CiAgICBpbXBvcnQgV2VsY29tZVNjcmVlbiBmcm9tICIkbGliL2NvbXBvbmVudHMvV2VsY29tZVNjcmVlbi5zdmVsdGUiOwogICAK">{}</script>

<WelcomeScreen/>

{#if showRegistration.showRegistration}
  <Registration/>
{/if}

<style ✂prettier:content✂="CiAgICAvKiBPcHRpb25hbDogQWRkIHN0eWxlcyBoZXJlICovCg=="></style>